#!/usr/bin/env python3
from html.parser import HTMLParser
import sys
import re
import requests


class LinkParser(HTMLParser):

    def handle_starttag(self, tag, attrs):
        if tag != 'a':
            return

        try:
            link = dict(attrs)['href']
        except KeyError:
            return

        match = re.search('/([^/]+).complete.latest.tar', link)

        if match is not None:
            print(match.group(1))


def read_page(url):
    r = requests.get(url, verify=False)
    assert r.status_code == 200
    return r.text


url = sys.argv[1]
parser = LinkParser()
parser.feed(read_page(url))
