#!/usr/bin/env python3
from html.parser import HTMLParser
import requests
import sys
import re

class LinkParser(HTMLParser):

    def handle_starttag(self, tag, attrs):
        if tag != 'a':
            return

        try:
            link = dict(attrs)['href']
        except KeyError:
            return

        match = re.search('/([^/]+).complete.latest.tar', link)

        if match is not None:
            print(match.group(1))


url = sys.argv[1]

r = requests.get(url)
assert r.status_code == 200

parser = LinkParser()
parser.feed(r.text)
