#!/usr/bin/env python3
from urllib.request import urlopen
from html.parser import HTMLParser
import sys
import re


class LinkParser(HTMLParser):

    def handle_starttag(self, tag, attrs):
        if tag != 'a':
            return

        try:
            link = dict(attrs)['href']
        except KeyError:
            return

        match = re.search('/([^/]+).complete.latest.tar', link)

        if match is not None:
            print(match.group(1))


def read_page(url):
    with urlopen(url) as f:
        return f.read().decode()


url = sys.argv[1]
parser = LinkParser()
parser.feed(read_page(url))
